namespace TodoApp;

/// <summary>
/// Represents a single to-do item in the application.
/// </summary>
/// <remarks>
/// This entity is designed for EF Core persistence. It includes metadata such as creation time
/// and completion status, and enforces that a <see cref="Title"/> must be provided.
/// </remarks>
public class TodoItem(string title)
{
	/// <summary>
    /// Gets or sets the unique identifier for the to-do item.
    /// </summary>
    /// <remarks>
    /// This property is treated as the primary key by EF Core. It is typically
    /// generated by the database when the entity is saved.
    /// </remarks>
	public int Id {	get; init; }

	/// <summary>
    /// Gets or sets the title or description of the to-do item.
    /// </summary>
    /// <remarks>
    /// This property is marked as <c>required</c>, meaning it must be set when creating
    /// a new <see cref="TodoItem"/>. It describes the task to be completed.
    /// </remarks>
	public string Title { get; init; } = title
		?? throw new ArgumentNullException(nameof(title));

	/// <summary>
    /// Gets or sets a value indicating whether the to-do item has been completed.
    /// </summary>
    /// <value>
    /// <c>true</c> if the item is completed; otherwise, <c>false</c>.
    /// </value>
    /// <remarks>
    /// Defaults to <c>false</c> when a new item is created.
    /// </remarks>
	public bool IsCompleted { get; set; }

	/// <summary>
    /// Gets the UTC date and time when the to-do item was created.
    /// </summary>
    /// <remarks>
    /// This property is initialized automatically when the entity is created
    /// and is immutable thereafter.
    /// </remarks>
	public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

}
